import 'package:lotoplay/models/draw.dart';
import 'package:lotoplay/models/lottery.dart';
import 'package:lotoplay/models/number.dart';

class Loterias {
  static List<Lottery> lotteries = [
    Lottery(name: 'Lotto Activo', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),
    //
    // Agrega las loterías restantes
    Lottery(name: 'La Granjita', draws: [
      Draw(name: '08:00 Am', numbers: generateNumbers()),
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),
    Lottery(name: 'Ruleta Activa', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),
    Lottery(name: 'Chance con Animalitos', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),
    Lottery(name: 'Lotto Rey', draws: [
      Draw(name: '09:30 Am', numbers: generateNumbers()),
      Draw(name: '10:30 Am', numbers: generateNumbers()),
      Draw(name: '11:30 Am', numbers: generateNumbers()),
      Draw(name: '12:30 M ', numbers: generateNumbers()),
      Draw(name: '13:30 Pm', numbers: generateNumbers()),
      Draw(name: '14:30 Pm', numbers: generateNumbers()),
      Draw(name: '15:30 Pm', numbers: generateNumbers()),
      Draw(name: '16:30 Pm', numbers: generateNumbers()),
      Draw(name: '17:30 Pm', numbers: generateNumbers()),
      Draw(name: '18:30 Pm', numbers: generateNumbers()),
      // Agrega los sorteos restantes para esta lotería
    ]),
    Lottery(name: 'Selva Plus', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),

    Lottery(name: 'Guacharo Activo', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers2()),
      Draw(name: '10:00 Am', numbers: generateNumbers2()),
      Draw(name: '11:00 Am', numbers: generateNumbers2()),
      Draw(name: '12:00 M ', numbers: generateNumbers2()),
      Draw(name: '13:00 Pm', numbers: generateNumbers2()),
      Draw(name: '14:00 Pm', numbers: generateNumbers2()),
      Draw(name: '15:00 Pm', numbers: generateNumbers2()),
      Draw(name: '16:00 Pm', numbers: generateNumbers2()),
      Draw(name: '17:00 Pm', numbers: generateNumbers2()),
      Draw(name: '18:00 Pm', numbers: generateNumbers2()),
      Draw(name: '19:00 Pm', numbers: generateNumbers2()),

      // Agrega los sorteos restantes para esta lotería
    ]),
    Lottery(name: 'Jungla Millonaria', draws: [
      Draw(name: '09:00 Am', numbers: generateNumbers()),
      Draw(name: '10:00 Am', numbers: generateNumbers()),
      Draw(name: '11:00 Am', numbers: generateNumbers()),
      Draw(name: '12:00 M ', numbers: generateNumbers()),
      Draw(name: '13:00 Pm', numbers: generateNumbers()),
      Draw(name: '14:00 Pm', numbers: generateNumbers()),
      Draw(name: '15:00 Pm', numbers: generateNumbers()),
      Draw(name: '16:00 Pm', numbers: generateNumbers()),
      Draw(name: '17:00 Pm', numbers: generateNumbers()),
      Draw(name: '18:00 Pm', numbers: generateNumbers()),
      Draw(name: '19:00 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),

    Lottery(name: 'La Ricachona', draws: [
      Draw(name: '09:10 Am', numbers: generateNumbers()),
      Draw(name: '10:10 Am', numbers: generateNumbers()),
      Draw(name: '11:10 Am', numbers: generateNumbers()),
      Draw(name: '12:10 M ', numbers: generateNumbers()),
      Draw(name: '13:10 Pm', numbers: generateNumbers()),
      Draw(name: '14:10 Pm', numbers: generateNumbers()),
      Draw(name: '15:10 Pm', numbers: generateNumbers()),
      Draw(name: '16:10 Pm', numbers: generateNumbers()),
      Draw(name: '17:10 Pm', numbers: generateNumbers()),
      Draw(name: '18:10 Pm', numbers: generateNumbers()),
      Draw(name: '19:10 Pm', numbers: generateNumbers()),

      // Agrega los sorteos restantes para esta lotería
    ]),

    Lottery(name: 'Lotto Activo RD', draws: [
      Draw(name: '09:30 Am', numbers: generateNumbers()),
      Draw(name: '10:30 Am', numbers: generateNumbers()),
      Draw(name: '11:30 Am', numbers: generateNumbers()),
      Draw(name: '12:30 M ', numbers: generateNumbers()),
      Draw(name: '13:30 Pm', numbers: generateNumbers()),
      Draw(name: '14:30 Pm', numbers: generateNumbers()),
      Draw(name: '15:30 Pm', numbers: generateNumbers()),
      Draw(name: '16:30 Pm', numbers: generateNumbers()),
      Draw(name: '17:30 Pm', numbers: generateNumbers()),
      Draw(name: '18:30 Pm', numbers: generateNumbers()),
      // Agrega los sorteos restantes para esta lotería
    ]),
  ];
}

List<Number> generateNumbers() {
  return [
    Number(value: '01 Carnero'),
    Number(value: '02 Toro'),
    Number(value: '03 Ciempies'),
    Number(value: '04 Alacran'),
    Number(value: '05 Leon'),
    Number(value: '06 Rana'),
    Number(value: '07 Perico'),
    Number(value: '08 Raton'),
    Number(value: '09 Aguila'),
    Number(value: '10 Tigre'),
    Number(value: '11 Gato'),
    Number(value: '12 Caballo'),
    Number(value: '13 Mono'),
    Number(value: '14 Paloma'),
    Number(value: '15 Zorro'),
    Number(value: '16 Oso'),
    Number(value: '17 Pavo'),
    Number(value: '18 Burro'),
    Number(value: '19 Chivo'),
    Number(value: '20 Cochino'),
    Number(value: '21 Gallo'),
    Number(value: '22 Camello'),
    Number(value: '23 Cebra'),
    Number(value: '24 Iguana'),
    Number(value: '25 Gallina'),
    Number(value: '26 Vaca'),
    Number(value: '27 Perro'),
    Number(value: '28 Zamuro'),
    Number(value: '29 Elefante'),
    Number(value: '30 Caiman'),
    Number(value: '31 Lapa'),
    Number(value: '32 Ardilla'),
    Number(value: '33 Pescado'),
    Number(value: '34 Venado'),
    Number(value: '35 Jirafa'),
    Number(value: '36 Culebra'),
    // Agrega los números restantes con sus animalitos correspondientes
  ];
}

List<Number> generateNumbers2() {
  return [
    Number(value: '00 Delfin'),
    Number(value: '0 Delfin'),
    Number(value: '01 Carnero'),
    Number(value: '02 Toro'),
    Number(value: '03 Ciempies'),
    Number(value: '04 Alacran'),
    Number(value: '05 Leon'),
    Number(value: '06 Rana'),
    Number(value: '07 Perico'),
    Number(value: '08 Raton'),
    Number(value: '09 Aguila'),
    Number(value: '10 Tigre'),
    Number(value: '11 Gato'),
    Number(value: '12 Caballo'),
    Number(value: '13 Mono'),
    Number(value: '14 Paloma'),
    Number(value: '15 Zorro'),
    Number(value: '16 Oso'),
    Number(value: '17 Pavo'),
    Number(value: '18 Burro'),
    Number(value: '19 Chivo'),
    Number(value: '20 Cochino'),
    Number(value: '21 Gallo'),
    Number(value: '22 Camello'),
    Number(value: '23 Cebra'),
    Number(value: '24 Iguana'),
    Number(value: '25 Gallina'),
    Number(value: '26 Vaca'),
    Number(value: '27 Perro'),
    Number(value: '28 Zamuro'),
    Number(value: '29 Elefante'),
    Number(value: '30 Caiman'),
    Number(value: '31 Lapa'),
    Number(value: '32 Ardilla'),
    Number(value: '33 Pescado'),
    Number(value: '34 Venado'),
    Number(value: '35 Jirafa'),
    Number(value: '36 Culebra'),

    Number(value: '37 Carnero'),
    Number(value: '38 Toro'),
    Number(value: '39 Ciempies'),
    Number(value: '40 Alacran'),
    Number(value: '41 Leon'),
    Number(value: '42 Rana'),
    Number(value: '43 Perico'),
    Number(value: '44 Raton'),
    Number(value: '45 Aguila'),
    Number(value: '46 Tigre'),
    Number(value: '47 Gato'),
    Number(value: '48 Caballo'),
    Number(value: '49 Mono'),
    Number(value: '50 Paloma'),
    Number(value: '51 Zorro'),
    Number(value: '52 Oso'),
    Number(value: '53 Pavo'),
    Number(value: '54 Burro'),
    Number(value: '55 Chivo'),
    Number(value: '56 Cochino'),
    Number(value: '57 Gallo'),
    Number(value: '58 Camello'),
    Number(value: '59 Cebra'),
    Number(value: '60 Iguana'),
    Number(value: '61 Gallina'),
    Number(value: '62 Vaca'),
    Number(value: '63 Perro'),
    Number(value: '64 Zamuro'),
    Number(value: '65 Elefante'),
    Number(value: '66 Caiman'),
    Number(value: '67 Lapa'),
    Number(value: '68 Ardilla'),
    Number(value: '69 Pescado'),
    Number(value: '70 Venado'),
    Number(value: '71 Jirafa'),
    Number(value: '72 Culebra'),
    Number(value: '73 Jirafa'),
    Number(value: '74 Culebra'),
    Number(value: '75 Jirafa'),
    Number(value: '76 Culebra'),

    // Agrega los números restantes con sus animalitos correspondientes
  ];
}
